### ISSUE TITLE
Allow using higher version of angular

### ISSUE THREAD

**Issue by gottfrois** [likeastore/ngDialog#244]
Hey guys,

Is it possible to allow angular version >= `1.3.x` ? I'm currently using angular 1.4 release candidate for my project and as a result I have 2 angular version loaded.

Thanks.

**Comment by egor-smirnov** [comment]
There is one open issue for Angular 1.4 - https://github.com/likeastore/ngDialog/issues/243. It blocks us from bumping Angular version in package.json / bower.json.

Will revisit this issue after solving #243

**Comment by gottfrois** [comment]
Issue seems fixed, would it be possible now to allow angular `1.4.x` please ?

**Comment by jorn86** [comment]
For some reason, Bower still tells me "ngDialog#0.4.0 depends on angular#~1.3.x which resolved to angular#1.3.17". 0.4.0 seems to be the latest version, in which this should be fixed.
Any suggestions?

**Comment by egor-smirnov** [comment]
@jorn86 that's because new version is still not published to bower / npm. Please use master branch.
@voronianski I guess it's time to publish next version to bower / npm to avoid further confusion.

**Comment by jbimberg** [comment]
+1 (although there is an issue with angular 1.4 and animations which prevents ngDialogs from being closed... but this can be worked around by setting disableAnimation to true when opening an ngDialog)

**Comment by egor-smirnov** [comment]
@jbimberg seems strange that it doesn't work with Angular 1.4. We are using Angular 1.4 with latest version of ngDialog at https://github.com/likeastore/ngDialog/blob/master/example/index.html. It works well so far.

I guess we might need more specific code examples for your case. Consider opening new issue for that and don't forget to prepare code example.

**Comment by jbimberg** [comment]
Sorry, you are right, animated close works. I omitted some css when adapting the styles to my project's, wasn't aware that application logic might be css-sensitive.

**Comment by brunomperes** [comment]
Does the upgrade break when using angular 1.3.x ?
