### ISSUE TITLE
WARNING: Tried to load angular more than once

### ISSUE THREAD

**Issue by aaroncmoore** [likeastore/ngDialog#297]
When I package ngDialog using npm it gives this warning:

WARNING: Tried to load angular more than once.

This is because angular is made a dependency for ng-dialog in packages.json and require('angular') is passed to the factory:

// CommonJS
module.exports = factory(require('angular'));

While there is a logic to this dependency (ngDialog does require angular), users of the package will need to require angular themselves before they use ngDialog to begin with.  Making it a package dependency is redundant and creates unnecessary packaging with a separate angular install in the node_modules directory.

You can pull out the depdency (or make it a DevDependency) and just remove require('angular') or replace it with simply angular as it will already be loaded.

**Comment by egor-smirnov** [comment]
Should be fixed in latest master branch. Look at this lines - https://github.com/likeastore/ngDialog/blob/master/js/ngDialog.js#L10-L13

**Comment by aaroncmoore** [comment]
My pulls from npm still show this:

if (typeof module !== 'undefined' && module.exports) {
        // CommonJS
        module.exports = factory(require('angular'));
    } else if (typeof define === 'function' && define.amd) {
        // AMD
        define(['angular'], factory);
    } else {
        // Global Variables
        factory(root.angular);
    }

Is the package not updated on npm?

**Comment by egor-smirnov** [comment]
yes, it's not updated..

**Comment by voronianski** [comment]
@egor-smirnov hey, I'm back :) there's a problem with update of npm package?

**Comment by egor-smirnov** [comment]
@voronianski I think we have issue opened for updating npm package here - https://github.com/likeastore/ngDialog/issues/293
